"""
For obvious reasons, I can't add everything. Feel free to PR changes!

The extensions use regular expressions.
"""

NOT_CATEGORIZED = -1

mimes = {
    "document": {
        "slide": [
            "pptx?",
            "pps",
            "odp",
        ],
        "spreadsheet": [
            "xlsx?",
            "xlr",
            "ods",
            "csv",
        ],
        "wordsheet": ["docx?", "pdf", "rtf", "odt", "wp[ds]", "md"],
        NOT_CATEGORIZED: ["text?", "txt"],
    },
    "archive": [
        "rar5?",
        "z(ip)?",
        "iso",
        "img",
        "rpm",
        "arj",
        "pkg",
        "tar",
        "[7g]?z",
        "deb",
        "cab",
    ],
    "package": {
        "executable": [
            "apk",
            "bat",
            "com",
            "exe",
            "gadget",
            "jar",
            "wsf",
        ],
        NOT_CATEGORIZED: {
            "bin",
            "dmg",
            "toast",
            "vcd",
            "msi",
        },
    },
    "music": [
        "aif",
        "cda",
        "midi?",
        "mp[3a]",
        "ogg",
        "wav",
        "wma",
        "wpl",
        "flac",
    ],
    "video": {
        "hls": ["m3u8?"],
        NOT_CATEGORIZED: [
            "3g[2p]",
            "avi",
            "flv",
            "h264",
            "m[4ko]v",
            "mp4",
            "mpe?g",
            "rm",
            "swf",
            "vob",
            "wmv",
        ],
    },
    "image": [
        "ai",
        "bmp",
        "gif",
        "ico",
        "jpe?g",
        "png",
        "psd?",
        "svg",
        "tif?",
        "cr2",
    ],
    "other": [
        "cpl",
        "cur",
        "dll",
        "dmp",
        "drv",
        "icns",
        "sys",
        "tmp",
        "whl",
        "log",
        "dat",
    ],
    "developer": [
        "py[cdw]?",
        "s?css",
        "h",
        "[tj]s",
        "c(pp)?",
        "sh",
        "swift",
        "dart",
        "class",
        "java",
    ],
    "configuration": [
        "conf",
        "in[if]",
        "reg",
        "ya?ml",
        "json",
        "plist",
        "xml",
        "toml",
        "sql(ite)?",
        "db",
    ],
}
