"""
For obvious reasons, I can't add everything. Feel free to PR changes!

The extensions use regular expressions.
"""

NOT_CATEGORIZED = -1


IGNORE = (
    "url",
    "lnk",
)

mimes = {
    "document": {
        "slide": [
            "pptx?",
            "pps",
            "odp",
        ],
        "spreadsheet": [
            "xlsx?",
            "xlr",
            "ods",
            "csv",
        ],
        "wordsheet": ["docx?", "pdf", "rtf", "odt", "wp[ds]", "md", "rst"],
        NOT_CATEGORIZED: ["text?", "txt"],
    },
    "archive": [
        "rar5?",
        "z(ip)?",
        "iso",
        "img",
        "rpm",
        "arj",
        "pkg",
        "tar",
        "[7g]?z",
        "deb",
        "cab",
    ],
    "package": {
        "executable": [
            "apk",
            "bat",
            "com",
            "exe",
            "gadget",
            "jar",
            "dll",
            "wsf",
        ],
        NOT_CATEGORIZED: {
            "bin",
            "dmg",
            "toast",
            "vcd",
            "msi",
        },
    },
    "music": [
        "aif",
        "cda",
        "midi?",
        "mp[3a]",
        "ogg",
        "wav",
        "wma",
        "wpl",
        "flac",
    ],
    "video": {
        "hls": ["m3u8?"],
        NOT_CATEGORIZED: [
            "3g[2p]",
            "avi",
            "flv",
            "h264",
            "m[4ko]v",
            "mp4",
            "mpe?g",
            "rm",
            "swf",
            "vob",
            "wmv",
        ],
    },
    "image": [
        "ai",
        "bmp",
        "gif",
        "ico",
        "jpe?g",
        "png",
        "psd?",
        "svg",
        "tif?",
        "cr2",
        "xcf",
    ],
    "other": [
        "cpl",
        "cur",
        "dmp",
        "drv",
        "icns",
        "sys",
        "tmp",
        "whl",
        "log",
        "dat",
    ],
    "developer": [
        "py[cdw]?",
        "s?css",
        "hh?",
        "[tj]s",
        "c(c|pp)?",
        "sh",
        "swift",
        "dart",
        "class",
        "java",
        "php[345]?",
        "go",
        "rb",
        "y",
        "vbs?",
        "pl",
        "lua",
        "m",
        "gitignore",
        "html?",
        "sample",
        "so",
        "kt",
        "hlsl",
        "vcxproj",
    ],
    "configuration": [
        "conf",
        "in[if]?",
        "reg",
        "ya?ml",
        "json",
        "plist",
        "xml",
        "toml",
        "sql(ite)?",
        "db",
        "env",
        "proto(buf|[2-4])?",
        "cfg",
        "properties",
        "lock",
        "clang-format",
        "md5",
        "gitkeep",
        "gitattributes",
        "gitmodules",
        "gitconfig",
        "cmake",
        "makefile",
        "editorconfig",
        "manifest",
    ],
    "font": ["fnt", "fon", "[ot]tf", "woff2?"],
}
